# Generated by Django 6.0.1 on 2026-01-17 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="数据集名称"
                    ),
                ),
                ("product", models.CharField(max_length=200, verbose_name="商品名称")),
                (
                    "creationtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "datasource",
                    models.CharField(max_length=50, verbose_name="数据来源"),
                ),
            ],
            options={
                "verbose_name": "数据集表",
                "verbose_name_plural": "数据集表",
                "db_table": "myapp_dataset",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=250, verbose_name="密码")),
                ("nickname", models.CharField(max_length=50, verbose_name="昵称")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="avatars/default_avatar.png",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, unique=True, verbose_name="邮箱"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="电话")),
                (
                    "registtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "usertype",
                    models.CharField(
                        choices=[("normal", "普通用户"), ("admin", "管理员")],
                        default="normal",
                        max_length=20,
                        verbose_name="用户类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户表",
                "verbose_name_plural": "用户表",
                "db_table": "myapp_user",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="用户昵称"
                    ),
                ),
                ("content", models.TextField(verbose_name="评论内容")),
                ("publishtime", models.DateTimeField(verbose_name="发布时间")),
                (
                    "score",
                    models.IntegerField(blank=True, null=True, verbose_name="评分"),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        db_column="dataset",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.dataset",
                        to_field="dataset",
                        verbose_name="数据集名称",
                    ),
                ),
            ],
            options={
                "verbose_name": "评论表",
                "verbose_name_plural": "评论表",
                "db_table": "myapp_comment",
            },
        ),
        migrations.AddField(
            model_name="dataset",
            name="username",
            field=models.ForeignKey(
                db_column="username",
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.user",
                to_field="username",
                verbose_name="用户名",
            ),
        ),
    ]
