# Generated by Django 6.0.1 on 2026-01-29 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_dataset_creationtime_alter_user_registtime"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emotype",
                    models.CharField(
                        blank=True,
                        default="暂无",
                        max_length=50,
                        null=True,
                        verbose_name="情感类别",
                    ),
                ),
                (
                    "emoscore",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="情感权重"
                    ),
                ),
                ("keyword", models.CharField(max_length=100, verbose_name="观点词")),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, default=0, null=True, verbose_name="准确性"
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        db_column="comment_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.comment",
                        verbose_name="评论id",
                    ),
                ),
            ],
            options={
                "verbose_name": "情感分析表",
                "verbose_name_plural": "情感分析表",
                "db_table": "myapp_sentiment",
            },
        ),
    ]
