# Generated by Django 6.0.1 on 2026-02-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_sentiment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentiment",
            name="keyword",
            field=models.CharField(
                blank=True,
                default="暂无",
                max_length=100,
                null=True,
                verbose_name="观点词",
            ),
        ),
    ]
