# Generated by Django 6.0.1 on 2026-03-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_sentiment_accuracy_dataset_hassentiment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentiment",
            name="keyword",
        ),
    ]
